/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author jesanher
 */
public class Ventana_caj extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_caj
     */
    public Ventana_caj() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Panel_Boton = new javax.swing.JPanel();
        CerrarSL = new javax.swing.JLabel();
        categoriaL = new javax.swing.JLabel();
        ProvvedoresL = new javax.swing.JLabel();
        MeterialesL = new javax.swing.JLabel();
        VentasL = new javax.swing.JLabel();
        EgresosL = new javax.swing.JLabel();
        IngresosL = new javax.swing.JLabel();
        ComprasL1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(9, 33, 71));

        Panel_Boton.setBackground(new java.awt.Color(26, 72, 142));

        CerrarSL.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        CerrarSL.setForeground(new java.awt.Color(255, 255, 255));
        CerrarSL.setText("Cerrar Sesion");
        CerrarSL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarSLMouseClicked(evt);
            }
        });

        categoriaL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        categoriaL.setForeground(new java.awt.Color(255, 255, 255));
        categoriaL.setText("Categoría");
        categoriaL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                categoriaLMouseClicked(evt);
            }
        });

        ProvvedoresL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ProvvedoresL.setForeground(new java.awt.Color(255, 255, 255));
        ProvvedoresL.setText("Proveedores");
        ProvvedoresL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProvvedoresLMouseClicked(evt);
            }
        });

        MeterialesL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        MeterialesL.setForeground(new java.awt.Color(255, 255, 255));
        MeterialesL.setText("Materiales");
        MeterialesL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MeterialesLMouseClicked(evt);
            }
        });

        VentasL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        VentasL.setForeground(new java.awt.Color(255, 255, 255));
        VentasL.setText("Ventas");
        VentasL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VentasLMouseClicked(evt);
            }
        });

        EgresosL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        EgresosL.setForeground(new java.awt.Color(255, 255, 255));
        EgresosL.setText("Egresos");
        EgresosL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EgresosLMouseClicked(evt);
            }
        });

        IngresosL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        IngresosL.setForeground(new java.awt.Color(255, 255, 255));
        IngresosL.setText("Ingresos");
        IngresosL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IngresosLMouseClicked(evt);
            }
        });

        ComprasL1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ComprasL1.setForeground(new java.awt.Color(255, 255, 255));
        ComprasL1.setText("Compras");
        ComprasL1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComprasL1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Panel_BotonLayout = new javax.swing.GroupLayout(Panel_Boton);
        Panel_Boton.setLayout(Panel_BotonLayout);
        Panel_BotonLayout.setHorizontalGroup(
            Panel_BotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_BotonLayout.createSequentialGroup()
                .addGroup(Panel_BotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_BotonLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CerrarSL))
                    .addGroup(Panel_BotonLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(Panel_BotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProvvedoresL)
                            .addComponent(categoriaL)
                            .addComponent(MeterialesL)
                            .addComponent(VentasL)
                            .addComponent(EgresosL)
                            .addComponent(ComprasL1)
                            .addComponent(IngresosL))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        Panel_BotonLayout.setVerticalGroup(
            Panel_BotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_BotonLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(categoriaL)
                .addGap(28, 28, 28)
                .addComponent(ProvvedoresL)
                .addGap(35, 35, 35)
                .addComponent(MeterialesL)
                .addGap(31, 31, 31)
                .addComponent(VentasL)
                .addGap(30, 30, 30)
                .addComponent(EgresosL)
                .addGap(30, 30, 30)
                .addComponent(ComprasL1)
                .addGap(29, 29, 29)
                .addComponent(IngresosL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(CerrarSL)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Panel_Boton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 489, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Panel_Boton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CerrarSLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarSLMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CerrarSLMouseClicked

    private void categoriaLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoriaLMouseClicked
        // TODO add your handling code here:
       // jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_categoriaLMouseClicked

    private void ProvvedoresLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProvvedoresLMouseClicked
        // TODO add your handling code here:
       // jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_ProvvedoresLMouseClicked

    private void MeterialesLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MeterialesLMouseClicked
        // TODO add your handling code here:
       // jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_MeterialesLMouseClicked

    private void VentasLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VentasLMouseClicked
        // TODO add your handling code here:
      //  jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_VentasLMouseClicked

    private void EgresosLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EgresosLMouseClicked
        // TODO add your handling code here:
       // jTabbedPane1.setSelectedIndex(6);
    }//GEN-LAST:event_EgresosLMouseClicked

    private void IngresosLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresosLMouseClicked
        // TODO add your handling code here:
       // jTabbedPane1.setSelectedIndex(5);
    }//GEN-LAST:event_IngresosLMouseClicked

    private void ComprasL1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComprasL1MouseClicked
        // TODO add your handling code here:
       // jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_ComprasL1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_caj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_caj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_caj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_caj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_caj().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CerrarSL;
    private javax.swing.JLabel ComprasL1;
    private javax.swing.JLabel EgresosL;
    private javax.swing.JLabel IngresosL;
    private javax.swing.JLabel MeterialesL;
    private javax.swing.JPanel Panel_Boton;
    private javax.swing.JLabel ProvvedoresL;
    private javax.swing.JLabel VentasL;
    private javax.swing.JLabel categoriaL;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
